### ISSUE TITLE
(FORGE) Error upon world creation (both on client and server)

### ISSUE THREAD

**Issue by Tsunamori74** [MoonflowerTeam/pollen#10]
### What version are you seeing the problem on?

1.18.x

### Describe the issue

```markdown
Launching my server fails on world load with a Pollen related issue (log mentions missing references) and clientside world creation also fails, not resulting in a crash but in a message noting that the mod datapacks failed to load and the game can continue if I revert to the vanilla datapack ("safe mode").

Steps:
1) Launch game/server
2) Attempt to create/load world
```

### latest.log

```shell
[13:08:23] [main/INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 39.0.79, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407]
[13:08:23] [main/INFO]: ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 17.0.1 by Oracle Corporation
[13:08:24] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/flclm/Desktop/Shin%20BB%20Forever%202/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319!/ Service=ModLauncher Env=SERVER
[13:08:25] [main/INFO]: Found mod file abnormals_delight-1.18.1-2.0.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file advancementframes-1.18-1.0.5.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file alloyed-1.18.1-v1.2.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file allurement-1.18.1-2.0.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file anchor-forge-1.0.0+1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file appleskin-forge-mc1.18-2.3.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file Architects-Palette-1.18.1-1.1.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file architectury-3.7.22.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file artifacts-1.18.1-4.0.2.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file AttributeFix-Forge-1.18.1-13.0.5.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file AutoRegLib-1.7-53.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file balm-2.4.3+0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file berry_good-1.18.1-5.0.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file blueprint-1.18.1-5.1.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file boatload-1.18.1-3.0.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file bottleyourxp_1.18.1-1.7.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file caelus-forge-1.18.1-3.0.0.2.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file chalk-1.18.1-1.2.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file Clumps-forge-1.18.1-8.0.0+5.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file collective-1.18.1-4.7.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file colytra-forge-1.18.1-5.2.0.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file Contact-Forge-1.18.1-1.1.2-Beta.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file Controlling-forge-1.18.1-9.0+15.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file corn_delight-1.0.4-1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file create-mc1.18.1_v0.4d.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file curioofundying-forge-1.18-5.3.0.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file curios-forge-1.18.1-5.0.6.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file CuriosQuarkOBP-1.18.1-1.1.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file curious-armor-stands-1.18.1-4.0.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file curiouselytra-forge-1.18.1-5.0.1.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file cyclepaintings_1.18.1-2.2.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file diet-forge-1.18.1-1.2.0.4.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file dismountentity_1.18.1-1.6.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file DustrialDecor-1.3.1-1.18.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file enchantedwolves-1.18.1-1.1.0.4.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file expandability-5.0.0-forge.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file FarmersDelight-1.18.1-1.0.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file FarmersDelight-1.18.1-1.0.3.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file FastLeafDecay-27.2.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file FastSuite-1.18.1-3.0.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file ferritecore-4.1.2-forge.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file flywheel-forge-1.18-0.6.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file geckolib-1.18-forge-3.0.11.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file handoveryouritems_1.18.1-1.4.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file hauntedharvest-1.18-1.7.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file heartstone-1.18-1.0.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file immersive-amethyst-1.1-forge-1.18.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file incubation-1.18.1-2.0.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file jei-1.18.1-9.2.3.84.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file krypton-1.0.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file locksmith-forge-1.0.0+1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file Lychee-1.18.1-forge-1.5.2.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file majobroom-1.4.0--1.18.1-forge.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file malum-1.18.1-1.2.2.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file mannequins-forge-2.0.0+1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file Map Atlases-forge-1.18.1-2.0.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file mmlib-1.0.0-1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file moreminecarts-1.4.3.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file MouseTweaks-forge-mc1.18-2.21.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file moyai-1.18-1.1.2.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file mutil-1.18.1-4.4.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file netherportalfix-forge-1.18-9.0.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file notenoughcrashes-4.1.4+1.18.1-forge.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file PackingTape-1.18-0.12.2.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file Patchouli-1.18.1-65.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file PatinaPipeworks-1.18.1-1.0.6-universal.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file personality-1.18.1-2.0.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file Placebo-1.18.1-6.1.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file pollen-forge-1.0.0+1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file polymorph-forge-1.18.1-0.35.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file pop-1.18-1.0.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file PuzzlesLib-v3.2.0-1.18.1-Forge.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file Quark-3.1-339.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file QuarkOddities-1.18.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file radium-0.7.7g.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file randomium-1.18.1-1.8.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file redstonepen-1.18.1-1.0.8.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file roasted-1.18.1-1.1.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file savage_and_ravage-1.18.1-4.0.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file selene-1.18-1.13.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file SereneSeasons-1.18.1-6.0.0.10-universal.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file shutupexperimentalsettings-1.0.4-1.18+.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file SilveroakOutpost-Forge-1.18-1.0.9-Alpha.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file skinned_lanterns-1.18.1-1.3.2.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file snowundertrees-1.18.1-1.2.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file snowyspirit-1.18-1.1.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file snuffles-1.0.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file Soft Drinks-forge-1.18.1-1.2.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file soundphysics-forge-1.18.1-1.0.4.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file sporeblossomspollinate-1.0.2.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file steampowered-1.18.1-2.0.0-alpha.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file SuperCircuitMaker2-0.2.0+1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file supplementaries-1.18.1-1.2.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file swingthroughgrass-1.18.1-1.8.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file tetra-1.18.1-4.6.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file TKLib-0.0.8+1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file villager-hats-mod-1.2.4.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file Wandering Trapper-forge-1.18.1-1.1.0.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file worldtime-1.18.1-forge39.0.9-1.3.1.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:25] [main/INFO]: Found mod file zetter-0.12.1-1.18.1-beta.jar of type MOD with locator {mods folder locator at C:\Users\flclm\Desktop\Shin BB Forever 2\mods}
[13:08:26] [main/INFO]: Found mod file fmlcore-1.18.1-39.0.79.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2bef51f2
[13:08:26] [main/INFO]: Found mod file javafmllanguage-1.18.1-39.0.79.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2bef51f2
[13:08:26] [main/INFO]: Found mod file mclanguage-1.18.1-39.0.79.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2bef51f2
[13:08:26] [main/INFO]: Found mod file server-1.18.1-20211210.034407-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2bef51f2
[13:08:26] [main/INFO]: Found mod file forge-1.18.1-39.0.79-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2bef51f2
[13:08:32] [main/INFO]: Compatibility level set to JAVA_17
[13:08:32] [main/ERROR]: Mixin config radium.mixins.json does not specify "minVersion" property
[13:08:32] [main/ERROR]: Mixin config supercircuitmaker.mixin.json does not specify "minVersion" property
[13:08:32] [main/ERROR]: Mixin config tklib.mixin.json does not specify "minVersion" property
[13:08:33] [main/INFO]: Successfully loaded Mixin Connector [com.sonicether.soundphysics.MixinConnector]
[13:08:33] [main/INFO]: Launching target 'forgeserver' with arguments []
[13:08:34] [main/WARN]: Reference map 'heartstone.refmap.json' for heartstone.mixins.json could not be read. If this is a development environment you can ignore this message
[13:08:34] [main/WARN]: Reference map 'environmental.refmap.json' for incubation.mixins.json could not be read. If this is a development environment you can ignore this message
[13:08:34] [main/ERROR]: Option util for dependency 'ai.nearby_entity_tracking depends on util=true' not found. Skipping.
[13:08:34] [main/ERROR]: Option entity.collisions.unpushable_cramming for dependency 'entity.collisions.unpushable_cramming depends on util=true' not found. Skipping.
[13:08:34] [main/ERROR]: Option entity.collisions.unpushable_cramming for dependency 'entity.collisions.unpushable_cramming depends on util.entity_section_position=true' not found. Skipping.
[13:08:34] [main/INFO]: Loaded configuration file for Radium: 101 options available, 0 override(s) found
[13:08:34] [main/WARN]: Reference map 'supercircuitmaker.refmap.json' for supercircuitmaker.mixin.json could not be read. If this is a development environment you can ignore this message
[13:08:34] [main/WARN]: Reference map 'tklib.refmap.json' for tklib.mixin.json could not be read. If this is a development environment you can ignore this message
[13:08:35] [main/INFO]: Patching ServerResources#<init>
[13:08:36] [main/FATAL]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[13:08:36] [main/WARN]: Error loading class: net/minecraft/client/Minecraft (java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER)
[13:08:36] [main/WARN]: @Mixin target net.minecraft.client.Minecraft was not found majobroom.mixins.json:MinecraftMixin
[13:08:42] [main/WARN]: @Inject(@At("HEAD")) Shift.BY=1 on blueprint.mixins.json:EntityMixin::handler$zbo000$baseTick exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[13:08:57] [modloading-worker-0/INFO]: Patching ServerResources#<init>
[13:08:57] [modloading-worker-0/INFO]: If you see this, everything is running at least as okay as a 3-legged hamster on amphetamines.
[13:08:58] [modloading-worker-0/INFO]: Redstone Pen GIT id #a870bef.
[13:08:58] [modloading-worker-0/WARN]: Method overwrite conflict for m_140184_ in radium.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin, previously written by me.steinborn.krypton.mixin.shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin. Skipping method.
[13:08:58] [modloading-worker-0/WARN]: Method overwrite conflict for sendChunks in radium.mixins.json:world.player_chunk_tick.ThreadedAnvilChunkStorageMixin, previously written by me.steinborn.krypton.mixin.shared.network.flushconsolidation.ThreadedAnvilChunkStorageMixin. Skipping method.
[13:08:59] [modloading-worker-0/INFO]: Forge mod loading, version 39.0.79, for MC 1.18.1 with MCP 20211210.034407
[13:08:59] [modloading-worker-0/INFO]: MinecraftForge v39.0.79 Initialized
[13:08:59] [modloading-worker-0/INFO]: Detected new forge version, registering events reflectively.
[13:09:00] [modloading-worker-0/INFO]: Detected new forge version, registering events reflectively.
[13:09:00] [modloading-worker-0/INFO]: Detected new forge version, registering events reflectively.
[13:09:02] [modloading-worker-0/INFO]: ExpandAbility here, who dis?
[13:09:08] [main/INFO]: HELLO from Register Block
[13:09:11] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `shulker_shell`, expected `supplementaries`. This could be a intended override, but in most cases indicates a broken mod.
[13:09:11] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `milk`, expected `forge`. This could be a intended override, but in most cases indicates a broken mod.
[13:09:11] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `flowing_milk`, expected `forge`. This could be a intended override, but in most cases indicates a broken mod.
[13:09:13] [main/WARN]: Configuration file C:\Users\flclm\Desktop\Shin BB Forever 2\config\hauntedharvest-common.toml is not correct. Correcting
[13:09:13] [main/WARN]: Incorrect key serene_seasons_compat.trick_or_treating_sub_seasons was corrected from [MID_AUTUMN, LATE_AUTUMN] to its default, [MID_AUTUMN, LATE_AUTUMN]. 
[13:09:13] [Thread-0/WARN]: Configuration file C:\Users\flclm\Desktop\Shin BB Forever 2\config\hauntedharvest-common.toml is not correct. Correcting
[13:09:13] [Thread-0/WARN]: Configuration file C:\Users\flclm\Desktop\Shin BB Forever 2\config\hauntedharvest-common.toml is not correct. Correcting
[13:09:13] [main/WARN]: Configuration file C:\Users\flclm\Desktop\Shin BB Forever 2\config\snowyspirit-common.toml is not correct. Correcting
[13:09:13] [main/WARN]: Incorrect key serene_seasons_compat.winter_season_sub_seasons was corrected from [MID_WINTER, LATE_WINTER] to its default, [MID_WINTER, LATE_WINTER]. 
[13:09:13] [main/INFO]: Loading Module Redstone Randomizer
[13:09:13] [main/INFO]: Loading Module Pistons Move Tile Entities
[13:09:13] [main/INFO]: Loading Module Obsidian Plate
[13:09:13] [main/INFO]: Loading Module Metal Buttons
[13:09:13] [main/INFO]: Loading Module Jukebox Automation
[13:09:13] [main/INFO]: Loading Module Iron Rod
[13:09:13] [main/INFO]: Loading Module Gravisand
[13:09:13] [main/INFO]: Loading Module Feeding Trough
[13:09:13] [main/INFO]: Loading Module Ender Watcher
[13:09:13] [main/INFO]: Loading Module Dispensers Place Blocks
[13:09:13] [main/INFO]: Loading Module Chute
[13:09:13] [main/INFO]: Loading Module Chains Connect Blocks
[13:09:13] [main/INFO]: Loading Module Wooden Posts
[13:09:13] [main/INFO]: Loading Module Vertical Slabs
[13:09:13] [main/INFO]: Loading Module Variant Ladders
[13:09:13] [main/INFO]: Loading Module Variant Furnaces
[13:09:13] [main/INFO]: Loading Module Variant Chests
[13:09:13] [main/INFO]: Loading Module Variant Bookshelves
[13:09:13] [main/INFO]: Loading Module Thatch
[13:09:13] [main/INFO]: Loading Module Sturdy Stone
[13:09:13] [main/INFO]: Loading Module Stools
[13:09:13] [main/INFO]: Loading Module Soul Sandstone
[13:09:13] [main/INFO]: Loading Module Shingles
[13:09:13] [main/INFO]: Loading Module Shear Vines
[13:09:13] [main/INFO]: Loading Module Rope
[13:09:13] [main/INFO]: Loading Module Oriental Palette
[13:09:13] [main/INFO]: Loading Module Nether Brick Fence Gate
[13:09:13] [main/INFO]: Loading Module More Stone Variants
[13:09:13] [main/INFO]: Loading Module More Potted Plants
[13:09:13] [main/INFO]: Loading Module More Brick Types
[13:09:13] [main/INFO]: Loading Module Midori
[13:09:13] [main/INFO]: Loading Module Leaf Carpet
[13:09:13] [main/INFO]: Loading Module Industrial Palette
[13:09:13] [main/INFO]: Loading Module Hedges
[13:09:13] [main/INFO]: Loading Module Grate
[13:09:13] [main/INFO]: Loading Module Gold Bars
[13:09:13] [main/INFO]: Loading Module Glass Item Frame
[13:09:13] [main/INFO]: Loading Module Framed Glass
[13:09:13] [main/INFO]: Loading Module Duskbound Blocks
[13:09:13] [main/INFO]: Loading Module Compressed Blocks
[13:09:13] [main/INFO]: Loading Module Celebratory Lamps
[13:09:13] [main/INFO]: Loading Module Quick Armor Swapping
[13:09:13] [main/INFO]: Loading Module Item Sharing
[13:09:13] [main/INFO]: Loading Module Inventory Sorting
[13:09:13] [main/INFO]: Loading Module Hotbar Changer
[13:09:13] [main/INFO]: Loading Module Expanded Item Interactions
[13:09:13] [main/INFO]: Loading Module Easy Transfering
[13:09:13] [main/INFO]: Loading Module Chests In Boats
[13:09:13] [main/INFO]: Loading Module Trowel
[13:09:13] [main/INFO]: Loading Module Slime In A Bucket
[13:09:13] [main/INFO]: Loading Module Seed Pouch
[13:09:13] [main/INFO]: Loading Module Pickarang
[13:09:13] [main/INFO]: Loading Module Pathfinder Maps
[13:09:13] [main/INFO]: Loading Module Endermosh Music Disc
[13:09:13] [main/INFO]: Loading Module Color Runes
[13:09:13] [main/INFO]: Loading Module Camera
[13:09:13] [main/INFO]: Loading Module Bundle Recipe
[13:09:13] [main/INFO]: Loading Module Bottled Cloud
[13:09:13] [main/INFO]: Loading Module Beacon Redirection
[13:09:13] [main/INFO]: Loading Module Ancient Tomes
[13:09:13] [main/INFO]: Loading Module Ambient Discs
[13:09:13] [main/INFO]: Loading Module Abacus
[13:09:13] [main/INFO]: Loading Module Villagers Follow Emeralds
[13:09:13] [main/INFO]: Loading Module Utility Recipes
[13:09:13] [main/INFO]: Loading Module Snow Golem Player Heads
[13:09:13] [main/INFO]: Loading Module Simple Harvest
[13:09:13] [main/INFO]: Loading Module Sign Editing
[13:09:13] [main/INFO]: Loading Module Replace Scaffolding
[13:09:13] [main/INFO]: Loading Module Reacharound Placing
[13:09:14] [main/INFO]: Loading Module Poison Potato Usage
[13:09:14] [main/INFO]: Loading Module Pat The Dogs
[13:09:14] [main/INFO]: Loading Module Note Block Mob Sounds
[13:09:14] [main/INFO]: Loading Module More Banner Layers
[13:09:14] [main/INFO]: Loading Module Lock Rotation
[13:09:14] [main/INFO]: Loading Module Hoe Harvesting
[13:09:14] [main/INFO]: Loading Module Glass Shard
[13:09:14] [main/INFO]: Loading Module Enhanced Ladders
[13:09:14] [main/INFO]: Loading Module Emotes
[13:09:14] [main/INFO]: Loading Module Dragon Scales
[13:09:14] [main/INFO]: Loading Module Double Door Opening
[13:09:14] [main/INFO]: Loading Module Compasses Work Everywhere
[13:09:14] [main/INFO]: Loading Module Campfires Boost Elytra
[13:09:14] [main/INFO]: Loading Module Better Elytra Rocket
[13:09:14] [main/INFO]: Loading Module Automatic Recipe Unlock
[13:09:14] [main/INFO]: Loading Module Armed Armor Stands
[13:09:14] [main/INFO]: Loading Module Skull Pikes
[13:09:14] [main/INFO]: Loading Module Spiral Spires
[13:09:14] [main/INFO]: Loading Module Permafrost
[13:09:14] [main/INFO]: Loading Module New Stone Types
[13:09:14] [main/INFO]: Loading Module Nether Obsidian Spikes
[13:09:14] [main/INFO]: Loading Module Monster Box
[13:09:14] [main/INFO]: Loading Module Glimmering Weald
[13:09:14] [main/INFO]: Loading Module Fairy Rings
[13:09:14] [main/INFO]: Loading Module Corundum
[13:09:14] [main/INFO]: Loading Module Chorus Vegetation
[13:09:15] [main/INFO]: Loading Module Blossom Trees
[13:09:15] [main/INFO]: Loading Module Big Stone Clusters
[13:09:15] [main/INFO]: Loading Module Big Dungeon
[13:09:15] [main/INFO]: Loading Module Azalea Wood
[13:09:15] [main/INFO]: Loading Module Wraith
[13:09:15] [main/INFO]: Loading Module Toretoise
[13:09:15] [main/INFO]: Loading Module Stonelings
[13:09:15] [main/INFO]: Loading Module Shiba
[13:09:15] [main/INFO]: Loading Module Frogs
[13:09:15] [main/INFO]: Loading Module Foxhound
[13:09:15] [main/INFO]: Loading Module Forgotten
[13:09:15] [main/INFO]: Loading Module Crabs
[13:09:15] [main/INFO]: Loading Module Variant Animal Textures
[13:09:15] [main/INFO]: Loading Module Usage Ticker
[13:09:15] [main/INFO]: Loading Module Soul Candles
[13:09:15] [main/INFO]: Loading Module Microcrafting Helper
[13:09:15] [main/INFO]: Loading Module Improved Tooltips
[13:09:15] [main/INFO]: Loading Module Greener Grass
[13:09:15] [main/INFO]: Loading Module Chest Searching
[13:09:15] [main/INFO]: Loading Module Back Button Keybind
[13:09:15] [main/INFO]: Loading Module Auto Walk Keybind
[13:09:15] [main/INFO]: Loading Module Overlay Shader
[13:09:15] [main/INFO]: Loading Module Narrator Readout
[13:09:15] [main/INFO]: Loading Module Game Nerfs
[13:09:15] [main/INFO]: Loading Module Adjustable Chat
[13:09:15] [main/INFO]: Loading Module Totem Of Holding
[13:09:15] [main/INFO]: Loading Module Pipes
[13:09:15] [main/INFO]: Loading Module Matrix Enchanting
[13:09:15] [main/INFO]: Loading Module Magnets
[13:09:15] [main/INFO]: Loading Module Crate
[13:09:15] [main/INFO]: Loading Module Backpack
[13:09:15] [modloading-worker-0/INFO]: Reloading config
[13:09:15] [modloading-worker-0/INFO]: Reloading reverb parameters
[13:09:15] [modloading-worker-0/INFO]: HELLO FROM PREINIT
[13:09:15] [modloading-worker-0/INFO]: DIRT BLOCK >> minecraft:dirt
[13:09:15] [modloading-worker-0/INFO]: Presented by Zaia
[13:09:15] [modloading-worker-0/INFO]: Compression will use Java 11, encryption will use Java
[13:09:16] [main/ERROR]: Failed to generate hanging sign recipe for wood type malum:runewood
[13:09:16] [main/ERROR]: Failed to generate hanging sign recipe for wood type malum:soulwood
[13:09:16] [main/ERROR]: Failed to generate hanging sign recipe for wood type quark:blossom
[13:09:16] [main/ERROR]: Failed to generate hanging sign recipe for wood type quark:azalea
[13:09:16] [main/ERROR]: Failed to generate sign post recipe for wood type quark:blossom
[13:09:16] [main/ERROR]: Failed to generate sign post recipe for wood type malum:soulwood
[13:09:16] [main/ERROR]: Failed to generate sign post recipe for wood type malum:runewood
[13:09:16] [main/ERROR]: Failed to generate sign post recipe for wood type quark:azalea
[13:09:16] [main/INFO]: Generated runtime data resources in: 0.22 seconds
[13:09:16] [Forge Version Check/INFO]: [sound_physics_remastered] Starting version check at https://maxhenkel.de/update/sound_physics_remastered.json
[13:09:17] [main/INFO]: Finished mod setup in: 0.676 seconds
[13:09:17] [modloading-worker-0/INFO]: Loaded values for 37 compatible attributes.
[13:09:17] [modloading-worker-0/ERROR]: Attribute ID 'chococraft:chocobo_max_stamina' does not belong to a known attribute. This entry will be ignored.
[13:09:17] [modloading-worker-0/INFO]: Loaded 38 values from config.
[13:09:17] [modloading-worker-0/INFO]: Saving config file. 38 entries.
[13:09:18] [modloading-worker-0/INFO]: Applying changes for 38 attributes.
[13:09:18] [Forge Version Check/INFO]: [sound_physics_remastered] Found status: UP_TO_DATE Current: 1.18.1-1.0.4 Target: null
[13:09:18] [Forge Version Check/INFO]: [controlling] Starting version check at https://updates.blamejared.com/get?n=controlling&gv=1.18.1
[13:09:18] [Forge Version Check/INFO]: [controlling] Found status: BETA Current: 9.0+15 Target: 9.0+15
[13:09:18] [Forge Version Check/INFO]: [sporeblossomspollinate] Starting version check at https://www.curseforge.com/minecraft/mc-mods/spore-blossoms-pollinate/files
[13:09:18] [Forge Version Check/WARN]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.Gson.fromJson(Gson.java:944) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.8.jar%2322!/:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:189) ~[fmlcore-1.18.1-39.0.79.jar%23140!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:128) [fmlcore-1.18.1-39.0.79.jar%23140!/:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2322!/:?]
	... 6 more
[13:09:18] [Forge Version Check/INFO]: [fastleafdecay] Starting version check at https://www.olafkeijsers.net/fastleafdecay-update.json
[13:09:19] [Forge Version Check/INFO]: [fastleafdecay] Found status: AHEAD Current: 27.2 Target: null
[13:09:19] [Forge Version Check/INFO]: [redstonepen] Starting version check at https://raw.githubusercontent.com/stfwi/redstonepen/1.17/meta/update.json
[13:09:19] [Forge Version Check/WARN]: Failed to process update information
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.Gson.fromJson(Gson.java:944) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.8.jar%2322!/:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:189) ~[fmlcore-1.18.1-39.0.79.jar%23140!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:128) [fmlcore-1.18.1-39.0.79.jar%23140!/:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.8.jar%2322!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar%2322!/:?]
	... 6 more
[13:09:19] [Forge Version Check/INFO]: [clumps] Starting version check at https://updates.blamejared.com/get?n=clumps&gv=1.18
[13:09:19] [Forge Version Check/INFO]: [clumps] Found status: BETA Current: 8.0.0+5 Target: null
[13:09:19] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[13:09:20] [Forge Version Check/INFO]: [forge] Found status: BETA_OUTDATED Current: 39.0.79 Target: 39.0.85
[13:09:20] [Forge Version Check/INFO]: [puzzleslib] Starting version check at https://raw.githubusercontent.com/Fuzss/modresources/main/update/puzzleslib.json
[13:09:20] [Forge Version Check/INFO]: [puzzleslib] Found status: AHEAD Current: 3.2.0 Target: null
[13:09:30] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:09:32] [main/WARN]: Assets URL 'union:/C:/Users/flclm/Desktop/Shin%20BB%20Forever%202/libraries/net/minecraft/server/1.18.1-20211210.034407/server-1.18.1-20211210.034407-srg.jar%23139!/assets/.mcassetsroot' uses unexpected schema
[13:09:32] [main/WARN]: Assets URL 'union:/C:/Users/flclm/Desktop/Shin%20BB%20Forever%202/libraries/net/minecraft/server/1.18.1-20211210.034407/server-1.18.1-20211210.034407-srg.jar%23139!/data/.mcassetsroot' uses unexpected schema
[13:09:33] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:09:33] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:09:33] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:09:33] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:09:33] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:09:33] [main/WARN]: Ambiguity between arguments [create, coupling, add, cart1] and [create, coupling, add, carts] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:09:33] [main/WARN]: Ambiguity between arguments [create, coupling, add, carts] and [create, coupling, add, cart1] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:09:33] [main/WARN]: Ambiguity between arguments [create, coupling, add, cart1] and [create, coupling, add, carts] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:09:34] [main/WARN]: Ambiguity between arguments [create, coupling, add, carts] and [create, coupling, add, cart1] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:09:34] [main/INFO]: Reloading ResourceManager: Default, SuperCircuitMaker2-0.2.0+1.18.1.jar, notenoughcrashes-4.1.4+1.18.1-forge.jar, netherportalfix-forge-1.18-9.0.0.jar, locksmith-forge-1.0.0+1.18.1.jar, Architects-Palette-1.18.1-1.1.0.jar, soundphysics-forge-1.18.1-1.0.4.jar, advancementframes-1.18-1.0.5.jar, Controlling-forge-1.18.1-9.0+15.jar, Placebo-1.18.1-6.1.1.jar, moreminecarts-1.4.3.jar, PatinaPipeworks-1.18.1-1.0.6-universal.jar, zetter-0.12.1-1.18.1-beta.jar, balm-2.4.3+0.jar, villager-hats-mod-1.2.4.jar, hauntedharvest-1.18-1.7.1.jar, TKLib-0.0.8+1.18.1.jar, FarmersDelight-1.18.1-1.0.3.jar, DustrialDecor-1.3.1-1.18.jar, curious-armor-stands-1.18.1-4.0.0.jar, moyai-1.18-1.1.2.jar, skinned_lanterns-1.18.1-1.3.2.jar, pop-1.18-1.0.0.jar, sporeblossomspollinate-1.0.2.jar, Soft Drinks-forge-1.18.1-1.2.1.jar, curios-forge-1.18.1-5.0.6.0.jar, tetra-1.18.1-4.6.0.jar, Patchouli-1.18.1-65.jar, enchantedwolves-1.18.1-1.1.0.4.jar, collective-1.18.1-4.7.jar, Wandering Trapper-forge-1.18.1-1.1.0.jar, architectury-3.7.22.jar, immersive-amethyst-1.1-forge-1.18.jar, curiouselytra-forge-1.18.1-5.0.1.0.jar, krypton-1.0.0.jar, anchor-forge-1.0.0+1.18.1.jar, FastLeafDecay-27.2.jar, geckolib-1.18-forge-3.0.11.jar, radium-0.7.7g.jar, QuarkOddities-1.18.jar, handoveryouritems_1.18.1-1.4.jar, redstonepen-1.18.1-1.0.8.jar, jei-1.18.1-9.2.3.84.jar, AttributeFix-Forge-1.18.1-13.0.5.jar, Map Atlases-forge-1.18.1-2.0.0.jar, caelus-forge-1.18.1-3.0.0.2.jar, CuriosQuarkOBP-1.18.1-1.1.0.jar, Contact-Forge-1.18.1-1.1.2-Beta.jar, colytra-forge-1.18.1-5.2.0.1.jar, SilveroakOutpost-Forge-1.18-1.0.9-Alpha.jar, FastSuite-1.18.1-3.0.0.jar, Clumps-forge-1.18.1-8.0.0+5.jar, shutupexperimentalsettings-1.0.4-1.18+.jar, artifacts-1.18.1-4.0.2.jar, SereneSeasons-1.18.1-6.0.0.10-universal.jar, worldtime-1.18.1-forge39.0.9-1.3.1.jar, curioofundying-forge-1.18-5.3.0.0.jar, snowundertrees-1.18.1-1.2.jar, bottleyourxp_1.18.1-1.7.jar, snuffles-1.0.1.jar, PackingTape-1.18-0.12.2.jar, dismountentity_1.18.1-1.6.jar, blueprint-1.18.1-5.1.1.jar, boatload-1.18.1-3.0.0.jar, savage_and_ravage-1.18.1-4.0.0.jar, allurement-1.18.1-2.0.0.jar, incubation-1.18.1-2.0.0.jar, berry_good-1.18.1-5.0.0.jar, randomium-1.18.1-1.8.jar, forge-1.18.1-39.0.79-universal.jar, chalk-1.18.1-1.2.0.jar, selene-1.18-1.13.0.jar, supplementaries-1.18.1-1.2.0.jar, swingthroughgrass-1.18.1-1.8.0.jar, MouseTweaks-forge-mc1.18-2.21.jar, snowyspirit-1.18-1.1.0.jar, majobroom-1.4.0--1.18.1-forge.jar, personality-1.18.1-2.0.0.jar, mmlib-1.0.0-1.18.1.jar, corn_delight-1.0.4-1.18.1.jar, flywheel-forge-1.18-0.6.0.jar, alloyed-1.18.1-v1.2.jar, steampowered-1.18.1-2.0.0-alpha.jar, create-mc1.18.1_v0.4d.jar, mutil-1.18.1-4.4.0.jar, diet-forge-1.18.1-1.2.0.4.jar, cyclepaintings_1.18.1-2.2.jar, malum-1.18.1-1.2.2.jar, polymorph-forge-1.18.1-0.35.jar, AutoRegLib-1.7-53.jar, Quark-3.1-339.jar, abnormals_delight-1.18.1-2.0.0.jar, appleskin-forge-mc1.18-2.3.0.jar, ferritecore-4.1.2-forge.jar, PuzzlesLib-v3.2.0-1.18.1-Forge.jar, Lychee-1.18.1-forge-1.5.2.jar, mannequins-forge-2.0.0+1.18.1.jar, pollen-forge-1.0.0+1.18.1.jar, heartstone-1.18-1.0.0.jar, expandability-5.0.0-forge.jar, roasted-1.18.1-1.1.0.jar
[13:09:34] [main/ERROR]: Parsing error loading custom data modifier anchor:creeper_loot_modifier: Cannot invoke "java.util.Deque.peek()" because the return value of "java.lang.ThreadLocal.get()" is null
[13:09:34] [main/ERROR]: Parsing error loading custom data modifier anchor:end_city_treasure_loot_modifier: Cannot invoke "java.util.Deque.peek()" because the return value of "java.lang.ThreadLocal.get()" is null
[13:09:34] [main/ERROR]: Parsing error loading custom data modifier anchor:simple_dungeon_loot_modifier: Cannot invoke "java.util.Deque.peek()" because the return value of "java.lang.ThreadLocal.get()" is null
[13:09:34] [main/ERROR]: Parsing error loading custom data modifier anchor:stronghold_corridor_loot_modifier: Cannot invoke "java.util.Deque.peek()" because the return value of "java.lang.ThreadLocal.get()" is null
[13:09:34] [main/ERROR]: Parsing error loading custom data modifier anchor:nether_bridge_loot_modifier: Cannot invoke "java.util.Deque.peek()" because the return value of "java.lang.ThreadLocal.get()" is null
[13:09:34] [main/INFO]: Loaded 0 data modifiers
[13:09:35] [Worker-Main-5/ERROR]: Couldn't load tag pollen:test as it is missing following references: pollen:test (from pollen-forge-1.0.0+1.18.1.jar),pollen:flowing_test (from pollen-forge-1.0.0+1.18.1.jar)
[13:09:37] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: com.google.gson.JsonSyntaxException: Missing type, expected to find a string
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:153) ~[server-1.18.1-20211210.034407-srg.jar%23139!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.18.1-39.0.79.jar%2323!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: com.google.gson.JsonSyntaxException: Missing type, expected to find a string
	at net.minecraft.util.GsonHelper.m_13906_(GsonHelper.java:112) ~[server-1.18.1-20211210.034407-srg.jar%23139!/:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getCondition(CraftingHelper.java:232) ~[forge-1.18.1-39.0.79-universal.jar%23143!/:?]
	at net.minecraftforge.common.crafting.CraftingHelper.processConditions(CraftingHelper.java:224) ~[forge-1.18.1-39.0.79-universal.jar%23143!/:?]
	at net.minecraftforge.common.crafting.CraftingHelper.processConditions(CraftingHelper.java:213) ~[forge-1.18.1-39.0.79-universal.jar%23143!/:?]
	at gg.moonflower.pollen.api.registry.forge.ResourceConditionRegistryImpl.test(ResourceConditionRegistryImpl.java:48) ~[pollen-forge-1.0.0+1.18.1.jar%23106!/:?]
	at gg.moonflower.pollen.api.registry.ResourceConditionRegistry.test(ResourceConditionRegistry.java) ~[pollen-forge-1.0.0+1.18.1.jar%23106!/:?]
	at gg.moonflower.pollen.api.resource.condition.ConditionalTagEntry.m_7657_(ConditionalTagEntry.java:29) ~[pollen-forge-1.0.0+1.18.1.jar%23106!/:?]
	at net.minecraft.tags.Tag$Builder.m_144371_(Tag.java:104) ~[server-1.18.1-20211210.034407-srg.jar%23139!/:?]
	at net.minecraft.tags.TagLoader.m_144533_(TagLoader.java:128) ~[server-1.18.1-20211210.034407-srg.jar%23139!/:?]
	at net.minecraft.tags.TagLoader.m_144523_(TagLoader.java:85) ~[server-1.18.1-20211210.034407-srg.jar%23139!/:?]
	at net.minecraft.tags.TagLoader.m_144509_(TagLoader.java:81) ~[server-1.18.1-20211210.034407-srg.jar%23139!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraft.tags.TagLoader.m_144523_(TagLoader.java:81) ~[server-1.18.1-20211210.034407-srg.jar%23139!/:?]
	at net.minecraft.tags.TagLoader.m_144515_(TagLoader.java:127) ~[server-1.18.1-20211210.034407-srg.jar%23139!/:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
	at net.minecraft.tags.TagLoader.m_144507_(TagLoader.java:127) ~[server-1.18.1-20211210.034407-srg.jar%23139!/:?]
	at net.minecraft.tags.TagLoader.m_144544_(TagLoader.java:138) ~[server-1.18.1-20211210.034407-srg.jar%23139!/:?]
	at net.minecraft.tags.TagManager.m_144587_(TagManager.java:74) ~[server-1.18.1-20211210.034407-srg.jar%23139!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by jacksonhardaway** [comment]
Fixed

**Comment by KKotik** [comment]
I compiled last version and seems like that still exist.

**Comment by KKotik** [comment]
[debug.log](https://github.com/MoonflowerTeam/pollen/files/8127539/debug.log)
[latest.log](https://github.com/MoonflowerTeam/pollen/files/8127540/latest.log)

**Comment by Xaidee** [comment]
Can confirm this problem still exists and has not been fixed, compiled from latest file changes as of writing this. Would be helpful to provide more info rather than marking the multiple variations of this error report as closed or fixed. Appreciate your guys work but like common just say you'll fix it within the next coming days or even weeks and pin it so others who are running into the same error know what's going on. Sorry if this comes off as aggressive at all, I know mod development isn't simple or easy and you should be able to take as much time as you need to address and fix errors. Thanks :)

**Comment by jacksonhardaway** [comment]
My fault, I misread the issue. Will reopen this until it's fixed.

**Comment by Xaidee** [comment]
Thanks ^-^

**Comment by KKotik** [comment]
Still an issue.. 
![image](https://user-images.githubusercontent.com/45950781/155733300-a9f3f408-e74d-4f7e-b5bd-ee58103d2fe4.png)

**Comment by KKotik** [comment]
[debug.log](https://github.com/MoonflowerTeam/pollen/files/8141939/debug.log)
[latest.log](https://github.com/MoonflowerTeam/pollen/files/8141940/latest.log)

**Comment by jacksonhardaway** [comment]
I can't seem to pinpoint the issue, it may be a mod incompatibility. Could you try pollen by itself? If it doesn't show the screen, could you find which mod causes it?

**Comment by jacksonhardaway** [comment]
Nevermind, seems like a commit slipped through when uploading Anchor, it's an issue with Anchor.
